### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by RosaWagner** [kosmynkab/Brygada-1918#7]
- [x] Add directory "Documentation" for twitter material (facultative, you can send it by mail otherwise), and images of the README.md.
- [x] Add requirements for virtual environmnent
- [x] write a tuto to build fonts (with python packages in a venv) for README.md
- [x] Add a gitignore (autosaved, ds store, env)

**Comment by kosmynkab** [comment]
The twitter material is in progress ;)
